module "env" {
  source = "./modules/env"
  env_name        = var.env_name
  aws_region      = var.aws_region
  vpc_id          = var.vpc_id
  subnet_id       = var.subnet_id
  instance_type   = var.instance_type
  ssh_public_key  = var.ssh_public_key
  app_repo        = var.app_repo
  app_branch      = var.app_branch
  payment_mode    = var.payment_mode
  datadog_api_key = var.datadog_api_key
  gremlin_team_id = var.gremlin_team_id
  gremlin_secret  = var.gremlin_secret
  db_username     = var.db_username
  db_password     = var.db_password
  dynamodb_table_name = var.dynamodb_table_name
  tags            = var.tags
}
